apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-aws-app-chart.fullname" . }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-aws-app-chart.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "my-aws-app-chart.name" . }}-backend
    spec:
      containers:
        - name: awesome-architects
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-aws-app-chart.fullname" . }}-backend
  labels:
    app.kubernetes.io/part-of: {{ include "my-aws-app-chart.name" . }}-backend
  annotations:
    prometheus.io/port: "metrics-port"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: {{ include "my-aws-app-chart.name" . }}-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: metrics-port
  type: {{ .Values.backend.service.type }}