apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app:  {{ .Values.backend.name }}
    spec:
      containers:
        - name: awesome-architects
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  labels:
    app.kubernetes.io/part-of: {{ .Values.backend.service.name }}
  annotations:
    prometheus.io/port: "metrics-port"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: metrics-port
  type: {{ .Values.backend.service.type }}