apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-aws-app-chart.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "my-aws-app-chart.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "my-aws-app-chart.name" . }}-frontend
    spec:
      containers:
        - name: awesome-architects
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
spec:
  selector:
    app: {{ include "my-aws-app-chart.name" . }}-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.frontend.service.type }}