backend:
  name: backend-deployment
  image: public.ecr.aws/m6p2m6g2/backend:22
  service:
    name: backend
    type: LoadBalancer
    port: 8080

frontend:
  name: frontend-deployment
  image: public.ecr.aws/m6p2m6g2/frontend:28
  service:
    name: frontend
    type: LoadBalancer
    port: 80

serviceMonitor:
  name: backend-service-monitor

  